Pipewire polybar script
polybar/polybar-scripts pull request #320
Opened 2021-04-18 04:02 UTC by victortrac

2021-11-02 03:30 UTC, jonringer commented
Is there any reason to delay this? There's still no pipewire internal module https://polybar.readthedocs.io/en/latest/user/actions.html

2021-11-02 04:11 UTC, victortrac commented
@x70b1 Would you mind reviewing?

2021-11-02 05:29 UTC, jonringer approved these changes
Was able to adapt this to nix use case in https://github.com/jonringer/nixpkgs-config/blob/e341f3e6a39a2bedc11f5b51fb05badf6c1aa040/nix/polybar.nix

![ksnip_20211101-222728](https://user-images.githubusercontent.com/7673602/139791571-ceb13350-dec2-4228-96f8-fcd6e6afdd00.png)

2021-11-08 22:40 UTC, victortrac commented
@jonringer I updated to use pamixer instead of pactl, which is a lot cleaner: https://github.com/polybar/polybar-scripts/pull/320/commits/67942681119101a295f3b8d82926adae4767881f

2021-11-23 10:13 UTC, patrickhener commented
Any plans on merging?

2021-11-23 10:16 UTC, x70b1 commented
Sorry for the delay, I will take a look at it later.

2021-11-23 23:10 UTC, x70b1 requested changes
@victortrac 

Nice work! 
I just added smaller notes.

2021-11-23 23:10 UTC, x70b1 commented on polybar-scripts/pipewire/README.md
> +# Script: pipewire
Lets rename the script and directory to `pipewire-simple`.

2021-11-23 23:10 UTC, x70b1 commented on polybar-scripts/pipewire/pipewire.sh
> +        echo " ${DEFAULT_SOURCE} |  ${VOLUME} ${DEFAULT_SINK}"
Please replace icons with `#` to make it easy to replace them.

2021-11-23 23:10 UTC, x70b1 commented on polybar-scripts/pipewire/pipewire.sh
> +    if [ "${action}" == "up" ]; then
A `case` statement is probably a good idea here.

2021-11-23 23:10 UTC, x70b1 commented on polybar-scripts/pipewire/pipewire.sh
> +#!/usr/bin/env bash
Use `/bin/sh`. Take  also a look at the CONTRIBUTING.md

2022-03-31 10:51 UTC, merged

2022-03-31 10:51 UTC, x70b1 commented
Awesome, thanks!