Added support for multi monitor setups to herbstluftwm workspace info
polybar/polybar-scripts pull request #321
Opened 2021-04-26 17:34 UTC by fanginoort

This adds support for using the info-hlwm-workspaces.sh script on a multi monitor setup.

It expects MONITOR environment variable to be set for each instance of polybar. If the MONITOR variable is not set this will still be working, however there will be no distinction between the different monitors.
This enables formatting the tags considering whether the current monitor is focused or not.

Also if one clicks on one of the tags in polybar, the script will ensure that the monitor is focused where the user clicked the tag. This prevents the effect that if one clicks a tag on an unfocused monitor, the tag will change on the other, focused monitor. This is eventually unexpected behaviour.

2021-05-13 10:52 UTC, x70b1 commented on polybar-scripts/info-hlwm-workspaces/info-hlwm-workspaces.sh
> -                    ':')
Why do you replace the existing cases instead of creating new ones?

2021-05-13 10:52 UTC, patrick96 requested changes
It would probably be a good idea to have a case for each state prefix instead of replacing some of the cases from before.

Otherwise this looks good :)

2021-05-13 10:53 UTC, patrick96 commented
Seems x70b1 was slightly faster :wink:

2021-05-17 15:22 UTC, fanginoort commented
I tried to change as little as possible, which however wasn't the smartest thing after all.
The new commit now includes one case for each state prefix with the comments comming right from herbstluftwm's documentation :)

2021-05-17 17:28 UTC, patrick96 approved these changes
LGTM!

2021-05-17 18:57 UTC, merged

2021-05-17 18:58 UTC, x70b1 commented
Thanks @fanginoort !