Add Mullvad VPN module with extended functionality
polybar/polybar-scripts pull request #343
Opened 2021-08-20 14:32 UTC by totoroot

There already is a script that simply displays the connection status to Mullvad VPN.

This is a script that toggles Mullvad VPN connection with `mullvad` command line client, shows the connection status and optionally the location of the VPN server currently connected to. It is possible to configure the module to cycle through available server locations on scroll too.

2021-11-23 23:25 UTC, x70b1 requested changes
Nice work! Lets replace vpn-mullvad-status.

2021-11-23 23:25 UTC, x70b1 commented on polybar-scripts/vpn-mullvad/README.md
> +# Script: vpn-mullvad
We should replace the existing script with your work.
Rename the script and directory to `vpn-mullvad-status`.

2021-11-23 23:25 UTC, x70b1 commented on polybar-scripts/vpn-mullvad/vpn-mullvad.sh
> +	"status") connection_status;;
Flags starting with -- would be better.

2021-11-23 23:25 UTC, x70b1 commented on polybar-scripts/vpn-mullvad/vpn-mullvad.sh
> +# list_city_shortcodes() {
Do we still need this function?

2021-11-23 23:25 UTC, x70b1 commented on polybar-scripts/vpn-mullvad/README.md
> +![vpn-mullvad](screenshots/1.png)
Add the screenshots to the main README.md.

2022-07-27 11:13 UTC, totoroot commented
Closing this in favour of PR #383

2022-07-27 11:13 UTC, closed without merging